language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

install:
  - if [ $TRAVIS_PHP_VERSION = "hhvm" ]; then composer install; fi
  - composer dump-autoload

script: phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_success: if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then
    composer require codeclimate/php-test-reporter;
    ./vendor/bin/test-reporter;
  fi
